<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE deck [
<!ELEMENT deck (marca)+>
<!ELEMENT marca (logoURL?, country?, flagURL?, url?, modelo+)>
<!ATTLIST marca nombre CDATA #REQUIRED>
<!ELEMENT logoURL (#PCDATA)>
<!ELEMENT country (#PCDATA)>
<!ELEMENT flagURL (#PCDATA)>
<!ELEMENT url (#PCDATA)>
<!ELEMENT modelo (generacion)+>
<!ATTLIST modelo nombre CDATA #REQUIRED>
<!ELEMENT generacion (auto)+>
<!ATTLIST generacion 
    nombre CDATA #REQUIRED
    añoInicio CDATA #REQUIRED
    añoFin CDATA #REQUIRED
>
<!ELEMENT auto (nombre, año, chasis, propulsion, velocidad, potencia, aceleracion, tipo, precio, imagen, enlace, bloques?, masimagenes?)>
<!ATTLIST auto 
    id CDATA #REQUIRED
    terminado (true | false) "false"
>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT año (#PCDATA)>
<!ELEMENT chasis (#PCDATA)>
<!ELEMENT propulsion (#PCDATA)>
<!ELEMENT velocidad (#PCDATA)>
<!ELEMENT potencia (#PCDATA)>
<!ELEMENT aceleracion (#PCDATA)>
<!ELEMENT tipo (#PCDATA)>
<!ELEMENT precio (#PCDATA)>
<!ELEMENT imagen (#PCDATA)>
<!ELEMENT enlace (#PCDATA)>
<!ELEMENT bloques (bloque)*>
<!ELEMENT bloque (imagenurl?, titulo, texto)>
<!ELEMENT imagenurl (#PCDATA)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT texto (#PCDATA)>
<!ELEMENT masimagenes (extraimagenurl)*>
<!ELEMENT extraimagenurl (#PCDATA)>
]>
<deck>
  <marca nombre="Aston Martin">
    <logoURL>https://upload.wikimedia.org/wikipedia/commons/a/a2/Aston_Martin_V8_Vantage_Roadster_%28Facelift%29_%E2%80%93_Logo%2C_26._Oktober_2012%2C_D%C3%BCsseldorf.jpg</logoURL>
    <country>Inglaterra</country>
    <flagURL>https://upload.wikimedia.org/wikipedia/commons/b/be/Flag_of_England.svg</flagURL>
    <url>https://www.altanave.uy/2024/10/aston-martin.html</url>
    <modelo nombre="DB5">
      <generacion nombre="Aston Martin DB5" añoInicio="1963" añoFin="1965">
        <auto id="66" terminado="true"><nombre>Aston Martin DB5</nombre><año>1964</año><chasis>Coupe 2 puertas</chasis><propulsion>Gasolina</propulsion><velocidad>240</velocidad><potencia>282</potencia><aceleracion>6,8</aceleracion><tipo>Deportivo</tipo><precio>1500000</precio><imagen>https://upload.wikimedia.org/wikipedia/commons/8/8b/1964_Aston_Martin_DB5_4.jpg</imagen><enlace>https://www.altanave.uy/2024/11/aston-martin-db5-1964-coupe.html</enlace><bloques><bloque><imagenurl>https://upload.wikimedia.org/wikipedia/commons/6/6f/Aston_Martin_DB5%2C_James_Bond_08.jpg</imagenurl><titulo>Aston Martin DB5 y James Bond: Un Ícono del Cine</titulo><texto>El Aston Martin DB5 es sinónimo de elegancia y sofisticación, y su asociación con la franquicia de James Bond ha cimentado su estatus como un ícono cultural. Desde su debut en la película "Goldfinger" en 1964, el DB5 ha sido el coche favorito del famoso agente 007, equipado con gadgets y tecnologías innovadoras que capturan la imaginación del público. Este modelo representa la conexión entre el lujo y la aventura. Su aparición en múltiples películas de Bond ha elevado su valor en el mercado de coleccionistas. La popularidad del DB5 ha consolidando su lugar como uno de los automóviles más reconocidos y venerados en la cultura popular.</texto></bloque><bloque><imagenurl>https://upload.wikimedia.org/wikipedia/commons/d/db/Aston_Martin_DB5_James_Bond_hotop2.JPG</imagenurl><titulo>Auto de james bond</titulo><texto>Repleto de gadgets le valió el apodo del «coche más famoso del mundo».
Parachoques hidráulicos, Ametralladoras delanteras, Escudo antibalas, Matrículas giratorias, chorro de aceite y un dispositivo que lanzaba clavos, Teléfono móvil, Radar a bordo, Panel de armas y asiento eyectable.</texto></bloque></bloques></auto>
        <auto id="68" terminado="true"><nombre>Aston Martin DB5</nombre><año>1964</año><chasis>Convertible 2 puertas</chasis><propulsion>Gasolina</propulsion><velocidad>231</velocidad><potencia>282</potencia><aceleracion>6,9</aceleracion><tipo>Deportivo</tipo><precio>1000000</precio><imagen>https://upload.wikimedia.org/wikipedia/commons/d/dc/1964_Aston_Martin_DB5_Convertible_LC.jpg</imagen><enlace>https://www.altanave.uy/2024/11/aston-martin-db5-1964-convertible.html</enlace><masimagenes><extraimagenurl>https://upload.wikimedia.org/wikipedia/commons/8/85/Aston_Martin_DB5_%285643331563%29.jpg</extraimagenurl><extraimagenurl>https://upload.wikimedia.org/wikipedia/commons/d/dc/Aston_Martin_DB5_Convertible%2C_Grand_Basel_2018_%28Ank_Kumar%2C_Infosys%29_02.jpg</extraimagenurl></masimagenes></auto>
        <auto id="67" terminado="true"><nombre>Aston Martin DB5 Vantage</nombre><año>1964</año><chasis>Coupe 2 puertas</chasis><propulsion>Gasolina</propulsion><velocidad>260</velocidad><potencia>325</potencia><aceleracion>6,2</aceleracion><tipo>Deportivo</tipo><precio>2000000</precio><imagen>https://upload.wikimedia.org/wikipedia/commons/8/87/1964_Aston_Martin_DB5_Vantage_LC23.jpg</imagen><enlace>https://www.altanave.uy/2024/11/aston-martin-db5-vantage-1964-coupe.html</enlace><bloques><bloque><imagenurl>https://upload.wikimedia.org/wikipedia/commons/7/78/1966_Aston_Martin_DB5_V8_Prototype_HCC22.jpg</imagenurl><titulo>DB5 vs DB5 Vantage</titulo><texto>El Aston Martin DB5 Vantage se presenta como una versión mejorada del icónico DB5 estándar, destacándose por su motor más potente que produce hasta 325 caballos de fuerza, en comparación con los 282 del modelo original. Además, el Vantage incorpora características adicionales que realzan su rendimiento y experiencia de conducción, como un sistema de suspensión más avanzado y frenos de mayor capacidad.</texto></bloque></bloques></auto>
      </generacion>
    </modelo>
    <modelo nombre="Vantage">
      <generacion nombre="Vantage 3era generacion" añoInicio="2005" añoFin="2018">
        <auto id="74"><nombre>Aston Martin Vantage V8</nombre><año>2009</año><chasis>Coupe 2 puertas</chasis><propulsion>Gasolina</propulsion><velocidad>290</velocidad><potencia>420</potencia><aceleracion>4,9</aceleracion><tipo>Deportivo</tipo><precio>60000</precio><imagen>https://upload.wikimedia.org/wikipedia/commons/e/eb/2009_Aston_Martin_Vantage_V8_2.jpg</imagen><enlace>https://www.altanave.uy/2024/11/aston-martin-vantage-v8-2009-coupe.html</enlace><bloques><bloque><imagenurl>https://upload.wikimedia.org/wikipedia/commons/6/61/Aston_Martin_V8_Vantage_-_Flickr_-_Alexandre_Pr%C3%A9vot_%2859%29.jpg</imagenurl><titulo>Que significa Vantage</titulo><texto>Vantage, significa ventaja en inglés.</texto></bloque><bloque><imagenurl>https://upload.wikimedia.org/wikipedia/commons/1/10/Grey_Aston_Martin_V8_Vantage_-_20090805.jpg</imagenurl><titulo>Aston Martin Vantage Motor</titulo><texto>El vehículo cuenta con un chasis compuesto por aleaciones de aluminio y magnesio, lo que le otorga un peso de 1570 kg. La versión mejorada incorporaba un motor V8 de 4,7 litros y 32 válvulas, capaz de generar una potencia máxima de 420 caballos de fuerza. Estaba disponible con una transmisión manual o automática de seis velocidades, destacándose por su suavidad y menor esfuerzo al momento de operar el sistema de cambio de marchas.</texto></bloque></bloques></auto>
      </generacion>
      <generacion nombre="Vantage 2018" añoInicio="2018" añoFin="2023">
        <auto id="75" terminado="false">
          <nombre>Aston Martin V8 Vantage</nombre>
          <año>2018</año>
          <chasis>Coupe 2 puertas</chasis>
          <propulsion>Gasolina</propulsion>
          <velocidad>314</velocidad>
          <potencia>503</potencia>
          <aceleracion>3,6</aceleracion>
          <tipo>Deportivo</tipo>
          <precio>130000</precio>
          <imagen>https://upload.wikimedia.org/wikipedia/commons/1/15/2018_Aston_Martin_Vantage_V8_Auto_2.jpg</imagen>
          <enlace>https://www.altanave.uy/2024/11/aston-martin-v8-vantage-coupe-de-2_53.html</enlace>
          <masimagenes>
            <extraimagenurl>https://upload.wikimedia.org/wikipedia/commons/0/0c/Aston_Martin_V8_Vantage_Genf_2018.jpg</extraimagenurl>
            <extraimagenurl>https://upload.wikimedia.org/wikipedia/commons/c/c5/2018_Aston_Martin_Vantage_V8_Auto_4.jpg</extraimagenurl>
          </masimagenes>
        </auto>
      </generacion>
      <generacion nombre="Vantage 2024" añoInicio="2024" añoFin="2025">
        <auto id="73" terminado="false">
          <nombre>Aston Martin V8 Vantage</nombre>
          <año>2024</año>
          <chasis>Coupe 2 puertas</chasis>
          <propulsion>Gasolina</propulsion>
          <velocidad>314</velocidad>
          <potencia>503</potencia>
          <aceleracion>3,6</aceleracion>
          <tipo>Deportivo</tipo>
          <precio>160000</precio>
          <imagen>https://upload.wikimedia.org/wikipedia/commons/8/81/2024_Aston_Martin_Vantage_V8_2.jpg</imagen>
          <enlace>https://www.altanave.uy/2024/11/aston-martin-v8-vantage-coupe-de-2.html</enlace>
          <bloques>
            <bloque>
              <imagenurl>https://upload.wikimedia.org/wikipedia/commons/6/6f/2024_Aston_Martin_Vantage_V8_F1_Safety_Car_5.jpg</imagenurl>
              <titulo>Que auto es el Safety Car en la Fórmula 1 </titulo>
              <texto>El Safety Car, o coche de seguridad, es un vehículo que entra a la pista para regular el ritmo de los autos de carrera cuando se presenta una situación de riesgo, como escombros, colisión o condiciones meteorológicas adversas. Su función es dar tiempo a los comisarios para restablecer la pista y garantizar la seguridad de los pilotos. Para la temporada 2024 es el Aston Martin Vantage.</texto>
            </bloque>
            <bloque>
              <imagenurl>https://upload.wikimedia.org/wikipedia/commons/7/7e/2024_Aston_Martin_Vantage_V8_F1_Safety_Car.jpg</imagenurl>
              <titulo>Aston Martin Safety Car</titulo>
              <texto>El Vantage se suma a la parrilla de Fórmula 1® en 2024 junto con 20 coches que llevan la velocidad al límite. Es el Safety Car oficial de la FIA de Fórmula 1® acompañando al equipo de Fernando Alonso y mostrando su rica tradición de competición. </texto>
            </bloque>
          </bloques>
        </auto>
      </generacion>
    </modelo>
    <modelo nombre="One-77">
      <generacion nombre="One-77" añoInicio="2011" añoFin="2011">
        <auto id="62" terminado="false">
          <nombre>One-77</nombre>
          <año>2011</año>
          <chasis>Coupe 2 puertas</chasis>
          <propulsion>Gasolina</propulsion>
          <velocidad>330</velocidad>
          <potencia>700</potencia>
          <aceleracion>3,5</aceleracion>
          <tipo>Deportivo</tipo>
          <precio>2500000</precio>
          <imagen>https://upload.wikimedia.org/wikipedia/commons/9/98/Aston_Martin_One-77_Blue.jpg</imagen>
          <enlace>https://www.altanave.uy/2024/10/one-77-coupe-de-2-puertas-2011.html</enlace>
          <masimagenes>
            <extraimagenurl>https://upload.wikimedia.org/wikipedia/commons/1/16/Aston_Martin_One-77_7.jpg</extraimagenurl>
            <extraimagenurl>https://upload.wikimedia.org/wikipedia/commons/6/60/Aston_Martin_One-77_4.jpg</extraimagenurl>
            <extraimagenurl>https://upload.wikimedia.org/wikipedia/commons/8/86/Aston_Martin_One-77_8.jpg</extraimagenurl>
            <extraimagenurl>https://upload.wikimedia.org/wikipedia/commons/9/98/Aston_Martin_One-77_5.jpg</extraimagenurl>
          </masimagenes>
        </auto>
      </generacion>
    </modelo>
  </marca>
  <marca nombre="Bugatti">
    <logoURL>https://upload.wikimedia.org/wikipedia/commons/a/a9/Bugatti_Logo.png</logoURL>
    <country>Francia</country>
    <flagURL>https://upload.wikimedia.org/wikipedia/commons/b/bc/Flag_of_France_%281794%E2%80%931815%2C_1830%E2%80%931974%2C_2020%E2%80%93present%29.svg</flagURL>
    <url>https://www.altanave.uy/2024/10/bugatti.html</url>
    <modelo nombre="Veyron">
      <generacion nombre="Bugatti Veyron" añoInicio="2005" añoFin="2015">
        <auto id="9" terminado="false">
          <nombre>Bugatti Veyron 16.4</nombre>
          <año>2005</año>
          <chasis>Coupe 2 puertas</chasis>
          <propulsion>Gasolina</propulsion>
          <velocidad>407</velocidad>
          <potencia>987</potencia>
          <aceleracion>2,5</aceleracion>
          <tipo>Superauto</tipo>
          <precio>1920000</precio>
          <imagen>https://upload.wikimedia.org/wikipedia/commons/6/6b/Bugatti_veyron_in_Tokyo.jpg</imagen>
          <enlace>https://www.altanave.uy/2024/10/bugatti-veyron-164-coupe-de-2-puertas.html</enlace>
          <bloques>
            <bloque>
              <imagenurl>https://upload.wikimedia.org/wikipedia/commons/c/c7/Bugatti_Veyron_16.4_2005_%2826779947960%29.jpg</imagenurl>
              <titulo>Bugatti Veyron Velocidad maxima</titulo>
              <texto>Este auto fue Récord de Velocidad. Alcanzando una velocidad impresionante de 431,072 km/h, el Veyron se consagró como el superdeportivo de producción legal más veloz del mundo, asegurando su lugar en el prestigioso Libro Guinness de los Récords.</texto>
            </bloque>
            <bloque>
              <imagenurl>https://upload.wikimedia.org/wikipedia/commons/7/74/Volkswagen_W16.jpg</imagenurl>
              <titulo>Bugatti Veyron Motor</titulo>
              <texto>En su época, la potencia del Veyron era sin igual, estableciendo un nuevo estándar en el mundo automotriz. Considerado el primer superdeportivo, su extraordinario rendimiento se debe a su motor W16 de 8.0 litros y cuatro turbocompresores. El primer SuperAuto</texto>
            </bloque>
            <bloque>
              <imagenurl>https://upload.wikimedia.org/wikipedia/commons/5/5d/Bugatti_Veyron_-_panoramio.jpg</imagenurl>
              <titulo>Súper Exclusivo</titulo>
              <texto>En 2011 se vendió el último Bugatti Veyron Coupé de una serie de 300 unidades, aunque su entrega se retrasó varios años. Para 2013, el modelo 400, sumando los 300 Coupé y 150 Roadster, también encontró dueño, completando la producción limitada de 450 ejemplares.</texto>
            </bloque>
            <bloque>
              <imagenurl>https://upload.wikimedia.org/wikipedia/commons/8/8e/Bugatti_Veyron_EB_16.4_%282008%29_%2852569212082%29.jpg</imagenurl>
              <titulo>Nombre Ganador</titulo>
              <texto>El nombre Veyron se inspiró en el legendario piloto Pierre Veyron, ganador de las 24 Horas de Le Mans en 1939 a bordo del Bugatti Type 57SC..</texto>
            </bloque>
          </bloques>
          <masimagenes>
            <extraimagenurl>https://upload.wikimedia.org/wikipedia/commons/2/25/Bugatti_Veyron_%2810842630425%29.jpg</extraimagenurl>
          </masimagenes>
        </auto>
      </generacion>
    </modelo>
  </marca>
  <marca nombre="De Lorean">
    <logoURL>https://upload.wikimedia.org/wikipedia/commons/1/12/DeLorean_Motor_Company_logo.svg</logoURL>
    <country>Estados Unidos</country>
    <flagURL>https://upload.wikimedia.org/wikipedia/commons/a/a4/Flag_of_the_United_States.svg</flagURL>
    <url>https://www.altanave.uy/2024/10/delorean-motor-company.html</url>
    <modelo nombre="DMC-12">
      <generacion nombre="De Lorean DMC-12" añoInicio="1981" añoFin="1982">
        <auto id="59" terminado="false">
          <nombre>DMC De Lorean</nombre>
          <año>1982</año>
          <chasis>Coupe 2 puertas</chasis>
          <propulsion>Gasolina</propulsion>
          <velocidad>209</velocidad>
          <potencia>130</potencia>
          <aceleracion>9,4</aceleracion>
          <tipo>Deportivo</tipo>
          <precio>86500 </precio>
          <imagen>https://upload.wikimedia.org/wikipedia/commons/6/63/DeLorean_DMC-12_%2815704582713%29.jpg</imagen>
          <enlace>https://www.altanave.uy/2024/10/de-lorean-dmc-12-coupe-de-2-puertas-1982.html</enlace>
          <bloques>
            <bloque>
              <imagenurl>https://upload.wikimedia.org/wikipedia/commons/3/35/DeLorean_DMC-12_%289979%29.jpg</imagenurl>
              <titulo>Delorean DMC-12</titulo>
              <texto>El DMC DeLorean es conocido como el DeLorean, ya que este fue el único modelo que fabricó dicha compañía. DMC-12 es su designación interna de preproducción. Sin embargo, el nombre DMC-12 nunca se usó para ventas o marketing del modelo de producción.</texto>
            </bloque>
            <bloque>
              <imagenurl>https://upload.wikimedia.org/wikipedia/commons/2/2c/Delorean_DMC-12_side.jpg</imagenurl>
              <titulo>DMC-12 Delorean</titulo>
              <texto>El prototipo fue conocido como «DSV-1».  Pero luego se conocio como DMC (DeLorean Motor Company) 12 . Ya que tenía como objetivo un precio de venta de $ 12.000 en el momento del lanzamiento.</texto>
            </bloque>
            <bloque>
              <imagenurl>https://upload.wikimedia.org/wikipedia/commons/8/86/DeLorean_DMC-12_with_doors_open.jpg</imagenurl>
              <titulo>Puertas alas de gaviota</titulo>
              <texto>El DeLorean se caracteriza por su carrocería con puertas de ala de gaviota y paneles de acero inoxidable sin pintura.</texto>
            </bloque>
            <bloque>
              <imagenurl>https://upload.wikimedia.org/wikipedia/commons/3/3e/1981_DMC_DeLorean_Time_Machine_%2853581570735%29.jpg</imagenurl>
              <titulo>Delorean Back to the future</titulo>
              <texto>“En mi opinión, si vas a construir una máquina del tiempo, ¿por qué no hacerlo con estilo?”. El DeLorean DMC-12, es el deportivo que eligió el Doc Brown para darle forma a su máquina del tiempo en Volver al Futuro. </texto>
            </bloque>
            <bloque>
              <imagenurl>https://upload.wikimedia.org/wikipedia/commons/f/fc/DeLorean_DMC-12_-_Back_to_the_Future_%E2%80%93_CeBIT_2016_15.jpg</imagenurl>
              <titulo>Auto volver al futuro</titulo>
              <texto>Cuando el vehículo alcanza una velocidad de 88 mph (142 km/h), inicia el viaje en el tiempo. En este momento, el condensador de flujo comienza a generar electricidad que se canaliza hacia la defensa del automóvil. Al mismo tiempo, la fricción de los neumáticos provoca llamas que emergen de ellos. Una vez que el auto alcanza esa velocidad, desaparece en una nube de partículas, dejando tras de sí un par de estelas de fuego, resultado de los efectos de la mecánica cuántica.</texto>
            </bloque>
          </bloques>
          <masimagenes>
            <extraimagenurl>https://upload.wikimedia.org/wikipedia/commons/d/da/1983_DeLorean_DMC-12%2C_front_right%2C_05-18-2024.jpg</extraimagenurl>
            <extraimagenurl>https://upload.wikimedia.org/wikipedia/commons/9/9c/1983_DeLorean_DMC-12%2C_rear_right%2C_05-18-2024.jpg</extraimagenurl>
            <extraimagenurl>https://upload.wikimedia.org/wikipedia/commons/4/43/1983_DMC_De_Lorean%2C_rear_left%2C_09-07-2024.jpg</extraimagenurl>
          </masimagenes>
        </auto>
      </generacion>
    </modelo>
  </marca>
  <marca nombre="Ferrari">
    <logoURL>https://upload.wikimedia.org/wikipedia/commons/d/d7/2013_Ferrari_458_Spider_%2873530347%29.jpeg</logoURL>
    <country>Italia</country>
    <flagURL>https://upload.wikimedia.org/wikipedia/commons/0/03/Flag_of_Italy.svg</flagURL>
    <url>https://www.altanave.uy/2024/10/ferrari.html</url>
    <modelo nombre="250 GTO">
      <generacion nombre="Serie I" añoInicio="1962" añoFin="1963">
        <auto id="14" terminado="false">
          <nombre>Ferrari 250 GTO</nombre>
          <año>1962</año>
          <chasis>Coupe 2 puertas</chasis>
          <propulsion>Gasolina</propulsion>
          <velocidad>280</velocidad>
          <potencia>286</potencia>
          <aceleracion>4,4</aceleracion>
          <tipo>Deportivo</tipo>
          <precio>70000000</precio>
          <imagen>https://upload.wikimedia.org/wikipedia/commons/0/08/1962_Ferrari_250_GTO_Scaglietti_Series_I.jpg</imagen>
          <enlace>https://www.altanave.uy/2024/10/ferrari-250-gto-coupe-de-2-puertas-1962.html</enlace>
        </auto>
      </generacion>
      <generacion nombre="Serie II" añoInicio="1964" añoFin="1964">
        <auto id="15" terminado="false">
          <nombre>Ferrari 250 GTO</nombre>
          <año>1964</año>
          <chasis>Coupe 2 puertas</chasis>
          <propulsion>Gasolina</propulsion>
          <velocidad>280</velocidad>
          <potencia>296</potencia>
          <aceleracion>4,6</aceleracion>
          <tipo>Deportivo</tipo>
          <precio>70000000</precio>
          <imagen>https://upload.wikimedia.org/wikipedia/commons/1/11/2021_Pebble_Tour_Ferrari_250_GTO_5573GT.jpg</imagen>
          <enlace>https://www.altanave.uy/2024/10/ferrari-250-gto-coupe-de-2-puertas-1964.html</enlace>
        </auto>
      </generacion>
    </modelo>
    <modelo nombre="Daytona">
      <generacion nombre="Daytona" añoInicio="1968" añoFin="1974">
        <auto id="22" terminado="false">
          <nombre>Ferrari 365 GTB/4 Daytona</nombre>
          <año>1974</año>
          <chasis>Coupe 2 puertas</chasis>
          <propulsion>Gasolina</propulsion>
          <velocidad>280</velocidad>
          <potencia>347</potencia>
          <aceleracion>5,7</aceleracion>
          <tipo>Deportivo</tipo>
          <precio>1000000</precio>
          <imagen>https://upload.wikimedia.org/wikipedia/commons/7/7e/Ferrari_Daytona_365_GTB4_LC22.jpg</imagen>
          <enlace>https://www.altanave.uy/2024/10/ferrari-365-gtb4-daytona-coupe-de-2.html</enlace>
        </auto>
        <auto id="23" terminado="false">
          <nombre>Ferrari 365 GTS/4 Daytona</nombre>
          <año>1973</año>
          <chasis>Convertible 2 puertas</chasis>
          <propulsion>Gasolina</propulsion>
          <velocidad>280</velocidad>
          <potencia>347</potencia>
          <aceleracion>5,3</aceleracion>
          <tipo>Deportivo</tipo>
          <precio>2000000</precio>
          <imagen>https://upload.wikimedia.org/wikipedia/commons/d/df/1973_Ferrari_Daytona_Spyder_Verde_Pino_front_left.jpg</imagen>
          <enlace>https://www.altanave.uy/2024/10/ferrari-365-gts4-daytona-convertible-de.html</enlace>
          <bloques>
            <bloque>
              <imagenurl>https://upload.wikimedia.org/wikipedia/commons/c/cc/1972_Ferrari_365_GTS4_Daytona.jpg</imagenurl>
              <titulo>Ferrari Miami Vice</titulo>
              <texto>James “Sony” Crockett (interpretado por Don Johnson) protagonista de Visio en Miami maneba un  Ferrari 365 GTS/4 Daytona Spider de 1972. En realidad se podía advertir que se trataba de réplicas (Chevrolet Corvette C3). Esto proboco que don Enzo se indignara al ver el éxito que estaban cosechando vehículos que eran una copia burda de su producto.</texto>
            </bloque>
          </bloques>
        </auto>
      </generacion>
      <generacion nombre="Daytona SP3" añoInicio="2022" añoFin="2025">
        <auto id="24" terminado="false">
          <nombre>Ferrari Daytona SP3</nombre>
          <año>2023</año>
          <chasis>Coupe 2 puertas</chasis>
          <propulsion>Gasolina</propulsion>
          <velocidad>341</velocidad>
          <potencia>823</potencia>
          <aceleracion>2,85</aceleracion>
          <tipo>Superauto</tipo>
          <precio>2000000</precio>
          <imagen>https://upload.wikimedia.org/wikipedia/commons/6/6f/Ferrari_Daytona_SP3.jpg</imagen>
          <enlace>https://www.altanave.uy/2024/10/ferrari-daytona-sp3-coupe-de-2-puertas.html</enlace>
        </auto>
      </generacion>
    </modelo>
    <modelo nombre="360 Modena">
      <generacion nombre="360 Modena" añoInicio="1999" añoFin="2005">
        <auto id="70" terminado="false">
          <nombre>Ferrari 360 Challenge Stradale</nombre>
          <año>2003</año>
          <chasis>Coupe 2 puertas</chasis>
          <propulsion>Gasolina</propulsion>
          <velocidad>300</velocidad>
          <potencia>419</potencia>
          <aceleracion>4,1</aceleracion>
          <tipo>Superauto</tipo>
          <precio>300000</precio>
          <imagen>https://upload.wikimedia.org/wikipedia/commons/b/b9/2000_Ferrari_360_Challenge_Stradale.jpg</imagen>
          <enlace>https://www.altanave.uy/2024/11/ferrari-360-challenge-stradale-coupe-de.html</enlace>
        </auto>
        <auto id="71" terminado="false">
          <nombre>Ferrari 360 Modena</nombre>
          <año>2000</año>
          <chasis>Coupe 2 puertas</chasis>
          <propulsion>Gasolina</propulsion>
          <velocidad>295</velocidad>
          <potencia>394</potencia>
          <aceleracion>4,6</aceleracion>
          <tipo>Deportivo</tipo>
          <precio>150000</precio>
          <imagen>https://upload.wikimedia.org/wikipedia/commons/1/15/Ferrari_360%2C_BAS_24%2C_Brussels_%28P1170344-RR%29.jpg</imagen>
          <enlace>https://www.altanave.uy/2024/11/ferrari-360-modena-coupe-de-2-puertas.html</enlace>
        </auto>
        <auto id="72" terminado="false">
          <nombre>Ferrari 360 Spider</nombre>
          <año>2001</año>
          <chasis>Convertible 2 puertas</chasis>
          <propulsion>Gasolina</propulsion>
          <velocidad>293</velocidad>
          <potencia>394</potencia>
          <aceleracion>4,6</aceleracion>
          <tipo>Deportivo</tipo>
          <precio>120000</precio>
          <imagen>https://upload.wikimedia.org/wikipedia/commons/1/1c/2001-ferrari-360-rc.jpg</imagen>
          <enlace>https://www.altanave.uy/2024/11/ferrari-360-spider-convertible-de-2.html</enlace>
        </auto>
      </generacion>
    </modelo>
    <modelo nombre="SF90">
      <generacion nombre="SF90" añoInicio="2021" añoFin="2025">
        <auto id="20" terminado="false">
          <nombre>Ferrari SF90 Stradale</nombre>
          <año>2021</año>
          <chasis>Coupe 2 puertas</chasis>
          <propulsion>Híbrido</propulsion>
          <velocidad>340</velocidad>
          <potencia>986</potencia>
          <aceleracion>2,5</aceleracion>
          <tipo>Deportivo</tipo>
          <precio>500000</precio>
          <imagen>https://upload.wikimedia.org/wikipedia/commons/e/ee/2021_Ferrari_SF90.jpg</imagen>
          <enlace>https://www.altanave.uy/2024/10/ferrari-sf90-stradale-coupe-de-2.html</enlace>
          <bloques>
            <bloque>
              <imagenurl>https://upload.wikimedia.org/wikipedia/commons/4/45/Ferrari_SF90%2C_BAS_24%2C_Brussels_%28P1170486-RR%29.jpg</imagenurl>
              <titulo>Ferrari Hybrid</titulo>
              <texto>Es el primer automóvil superdeportivo híbrido eléctrico enchufable producido por el fabricante italiano Ferrari </texto>
            </bloque>
            <bloque>
              <imagenurl>https://upload.wikimedia.org/wikipedia/commons/a/aa/Ferrari_SF90%2C_BAS_24%2C_Brussels_%28P1170502-RR%29.jpg</imagenurl>
              <titulo>Ferrari SF90 Hybrid</titulo>
              <texto>En el modo E-Drive, el coche utiliza solo sus motores eléctricos para un desplazamiento totalmente eléctrico. 
En el modo híbrido (predeterminado), se combinan el motor de gasolina y los motores eléctricos;  que, gracias a un sistema de control, apaga el motor de gasolina para ahorrar combustible, reactivándolo cuando el conductor lo necesita. 
El modo Performance mantiene el motor encendido para recargar la batería y mejorar la respuesta del vehículo, optimizando el rendimiento. 
Finalmente, el modo Quality aprovecha al máximo la potencia del sistema motriz para un desempeño superior.</texto>
            </bloque>
          </bloques>
        </auto>
        <auto id="21" terminado="false">
          <nombre>Ferrari SF90 Spider</nombre>
          <año>2023</año>
          <chasis>Techo rígido de 2 puertas</chasis>
          <propulsion>Híbrido</propulsion>
          <velocidad>340</velocidad>
          <potencia>986</potencia>
          <aceleracion>2,5</aceleracion>
          <tipo>Deportivo</tipo>
          <precio>500000</precio>
          <imagen>https://upload.wikimedia.org/wikipedia/commons/2/24/Ferrari_reims_1200871.jpg</imagen>
          <enlace>https://www.altanave.uy/2024/10/ferrari-sf90-spider-techo-rigido-de-2.html</enlace>
        </auto>
        <auto id="79" terminado="false">
          <nombre>Ferrari SF90 Stradale Assetto Fiorano</nombre>
          <año>2024</año>
          <chasis>Coupe 2 puertas</chasis>
          <propulsion>Híbrido</propulsion>
          <velocidad>340</velocidad>
          <potencia>986</potencia>
          <aceleracion>2,5</aceleracion>
          <tipo>Superauto</tipo>
          <precio>625000</precio>
          <imagen>https://upload.wikimedia.org/wikipedia/commons/1/1e/Ferrari_SF90_Stradale.jpg</imagen>
          <enlace>https://www.altanave.uy/2024/11/ferrari-sf90-stradale-assetto-fiorano.html</enlace>
          <bloques>
            <bloque>
              <imagenurl>https://upload.wikimedia.org/wikipedia/commons/1/14/Ferrari_SF90_Stradale_Assetto_Fiorano_front.png</imagenurl>
              <titulo>Ferrari SF90 Assetto Fiorano</titulo>
              <texto>Peso reducido gracias a la inclusión de piezas de fibra de carbono y titanio, lo que le otorga un margen adicional en su agilidad y capacidad de frenado.</texto>
            </bloque>
            <bloque>
              <imagenurl>https://upload.wikimedia.org/wikipedia/commons/7/7b/2021_Ferrari_SF90_Assetto_Fiorano_2.jpg</imagenurl>
              <titulo>Ferrari SF90 af</titulo>
              <texto>Suspensión mejorada y un alerón trasero para maximizar el rendimiento en pista.</texto>
            </bloque>
          </bloques>
        </auto>
      </generacion>
    </modelo>
    <modelo nombre="458">
      <generacion nombre="458" añoInicio="2010" añoFin="2015">
        <auto id="28" terminado="false">
          <nombre>Ferrari 458 Italia</nombre>
          <año>2012</año>
          <chasis>Coupe 2 puertas</chasis>
          <propulsion>Gasolina</propulsion>
          <velocidad>325</velocidad>
          <potencia>570</potencia>
          <aceleracion>3,4</aceleracion>
          <tipo>Deportivo</tipo>
          <precio>200000</precio>
          <imagen>https://upload.wikimedia.org/wikipedia/commons/c/c2/2012_Ferrari_458_4.jpg</imagen>
          <enlace>https://www.altanave.uy/2024/10/ferrari-458-italia-coupe-de-2-puertas.html</enlace>
        </auto>